apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-github-rankings-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-k8s-github-rankings-app
  template:
    metadata:
      labels:
        app: nodejs-k8s-github-rankings-app
    spec:
      containers:
      - name: nodejs-k8s-github-rankings
        image: {{ .Values.deployment.image }}
        env:
          - name: MONGODB_HOSTNAME
            value: {{ .Values.mongodb.host }}
          - name: MONGODB_DBNAME
            value: {{ .Values.mongodb.database }}
          - name: MONGODB_USERNAME
            value: {{ .Values.mongodb.username }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.mongodb.password }}
      imagePullSecrets:
        - name: docker-credentials
